# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-30 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='\u65b0\u95fb\u6807\u9898', max_length=100)),
                ('contents', models.TextField(help_text='\u65b0\u95fb\u5185\u5bb9')),
                ('image', models.URLField(help_text='\u56fe\u7247\u5730\u5740', null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='\u65b0\u95fb\u521b\u5efa\u65f6\u95f4')),
                ('occurd_time', models.CharField(help_text='\u65b0\u95fb\u53d1\u751f\u65f6\u95f4', max_length=50)),
                ('auth', models.CharField(help_text='\u65b0\u95fb\u4f5c\u8005', max_length=50)),
                ('source', models.CharField(help_text='\u65b0\u95fb\u6765\u6e90', max_length=100)),
                ('source_url', models.URLField(help_text='\u65b0\u95fb\u6765\u6e90\u5730\u5740', null=True)),
                ('type', models.CharField(choices=[('entertainment', '\u5a31\u4e50'), ('economic', '\u8d22\u7ecf'), ('political ', '\u65f6\u653f'), ('agricultural ', '\u519c\u4e1a'), ('recruitment', '\u62db\u8058')], help_text='\u65b0\u95fb\u7c7b\u522b', max_length=50)),
            ],
            options={
                'ordering': ('-occurd_time',),
            },
        ),
    ]
