# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-30 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anthology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.CharField(default=1, help_text='\u5267\u96c6', max_length=40)),
                ('path', models.URLField(help_text='\u89c6\u9891\u64ad\u653e\u5730\u5740')),
                ('player', models.CharField(help_text='\u64ad\u653e\u5668', max_length=20, null=True)),
            ],
            options={
                'ordering': ('episode',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u89c6\u9891\u540d\u79f0', max_length=200, unique=True)),
                ('poster', models.URLField(help_text='\u89c6\u9891\u6d77\u62a5', null=True)),
                ('language', models.CharField(help_text='\u8bed\u8a00', max_length=80, null=True)),
                ('area', models.CharField(help_text='\u5730\u533a', max_length=80, null=True)),
                ('year', models.CharField(help_text='\u53d1\u884c\u65f6\u95f4', max_length=50, null=True)),
                ('actor', models.CharField(help_text='\u6f14\u5458', max_length=2000, null=True)),
                ('director', models.CharField(help_text='\u5bfc\u6f14', max_length=1000, null=True)),
                ('des', models.TextField(help_text='\u4ecb\u7ecd', null=True)),
                ('last_sync_time', models.CharField(help_text='\u6700\u540e\u66f4\u65b0\u65f6\u95f4', max_length=50, null=True)),
            ],
            options={
                'ordering': ('name', '-last_sync_time'),
            },
        ),
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u89c6\u9891\u79cd\u7c7b', max_length=60, unique=True)),
                ('type_name', models.CharField(help_text='\u7535\u5f71|\u7535\u89c6\u5267|\u76f4\u64ad', max_length=60, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.ForeignKey(help_text='\u89c6\u9891\u7c7b\u578b', on_delete=django.db.models.deletion.CASCADE, to='video.VideoType'),
        ),
        migrations.AddField(
            model_name='anthology',
            name='video',
            field=models.ForeignKey(help_text='\u89c6\u9891\u540d\u79f0', on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
    ]
