# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-30 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videotype',
            old_name='type_name',
            new_name='type',
        ),
    ]
