# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-30 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20181030_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotype',
            name='type',
        ),
    ]
